"""texts

Revision ID: 1d5ae3d54109
Revises: a534bc0e44f6
Create Date: 2020-01-28 18:27:46.727107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5ae3d54109'
down_revision = 'a534bc0e44f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_date'), 'text', ['date'], unique=False)
    op.drop_index('ix_texts_date', table_name='texts')
    op.drop_table('texts')
    op.add_column('handover', sa.Column('access_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handover', 'access_hash')
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('media_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_texts_date', 'texts', ['date'], unique=False)
    op.drop_index(op.f('ix_text_date'), table_name='text')
    op.drop_table('text')
    # ### end Alembic commands ###
